# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-07 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('backcolor', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Drb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mane', models.CharField(max_length=100)),
                ('tits', models.CharField(max_length=100)),
                ('price1', models.CharField(max_length=20)),
                ('price2', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('bprice', models.CharField(max_length=30)),
                ('mprice', models.CharField(max_length=30)),
                ('trackid', models.CharField(max_length=50)),
                ('num', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=100)),
                ('img1', models.CharField(max_length=100)),
                ('img2', models.CharField(max_length=100)),
                ('img3', models.CharField(max_length=100)),
                ('img4', models.CharField(max_length=100)),
                ('img5', models.CharField(max_length=100)),
                ('kuaj', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mrb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('token', models.CharField(default='', max_length=256)),
                ('headimg', models.CharField(default='img/atom.png', max_length=100)),
            ],
        ),
    ]
