# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaifang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
