# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaifang', '0002_auto_20181030_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headimg',
            field=models.CharField(default='img/atom.png', max_length=100),
        ),
    ]
