# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaifang', '0003_user_headimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('backcolor', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
            ],
        ),
    ]
