# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaifang', '0005_mrb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mane', models.CharField(max_length=100)),
                ('tits', models.CharField(max_length=100)),
                ('price1', models.CharField(max_length=20)),
                ('price2', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
            ],
        ),
    ]
