# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-03 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaifang', '0006_drb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('bprice', models.CharField(max_length=30)),
                ('mprice', models.CharField(max_length=30)),
                ('trackid', models.CharField(max_length=50)),
                ('num', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=100)),
                ('img1', models.CharField(max_length=100)),
                ('img2', models.CharField(max_length=100)),
                ('img3', models.CharField(max_length=100)),
                ('img4', models.CharField(max_length=100)),
                ('img5', models.CharField(max_length=100)),
                ('kuaj', models.BooleanField(default='false')),
            ],
        ),
    ]
