# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-03 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babaifang', '0007_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='kuaj',
            field=models.BooleanField(default=False),
        ),
    ]
